[package]
name = "scout_loader"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
flate2 = "1.0"
lazy_static = "1"
md5 = "0.8"
mongodb = "2"
regex = "1"
rust-htslib = "*"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

