use crate::utils::hash::generate_md5_key;
use crate::models::variant::Compound;

/// Parses compound annotations from Genmod output.
///
/// Compound annotations are generated by Genmod software and contain
/// information about related variants. The parser extracts compound entries
/// belonging to the provided case ID and creates compound objects containing
/// a display name, a variant identifier, and a score.
///
/// Scout IDs do not use the `chr` prefix in chromosome names, so any `chr`
/// prefix is removed from compound names before generating identifiers.
///
/// The case ID is required to generate the correct compound variant ID,
/// and the variant type (`clinical` or `research`) is included in the
/// identifier generation.
///
/// # Arguments
///
/// * `compound_info` - Optional raw compound annotation string from Genmod.
/// * `case_id` - Identifier of the case used to select matching compound entries.
/// * `variant_type` - Variant type (`clinical` or `research`) used when generating IDs.
///
/// # Returns
///
/// A vector of compound objects containing:
/// * `display_name` - Compound variant name without a `chr` prefix.
/// * `variant` - MD5 identifier generated from the compound name, variant type,
///   and case ID.
/// * `score` - Compound score provided by Genmod, or `0.0` if unavailable.
pub fn parse_compounds(
    compound_info: Option<String>,
    case_id: &str,
    variant_type: &str,
) -> Vec<Compound> {
    let mut compounds = Vec::new();

    let Some(compound_info) = compound_info else {
        return compounds;
    };

    for family_info in compound_info.split(',') {
        let split_entry: Vec<&str> = family_info.split(':').collect();

        // The first element is the family/case ID
        if split_entry.first() != Some(&case_id) {
            continue;
        }

        if split_entry.len() < 2 {
            continue;
        }

        for compound in split_entry[1].split('|') {
            let split_compound: Vec<&str> = compound.split('>').collect();

            if split_compound.is_empty() {
                continue;
            }

            let compound_name = split_compound[0]
                .trim_start_matches("chr");

            let variant_id = generate_md5_key(
                &compound_name
                    .split('_')
                    .chain(std::iter::once(variant_type))
                    .chain(std::iter::once(case_id))
                    .collect::<Vec<_>>(),
            );

            let score = split_compound
                .get(1)
                .and_then(|value| value.parse::<f64>().ok())
                .unwrap_or(0.0);

            compounds.push(Compound {
                display_name: compound_name.to_string(),
                variant: variant_id,
                score,
            });
        }
    }

    compounds
}