use crate::models::variant::Compound;
use crate::utils::hash::generate_md5_key;
use mongodb::bson::{Bson, Document, doc};
use std::collections::HashMap;

use crate::loader::Loader;

/// Parses compound annotations from Genmod output.
///
/// Compound annotations are generated by Genmod software and contain
/// information about related variants. The parser extracts all compound
/// entries and creates compound objects containing a display name, a variant
/// identifier, and a score.
///
/// Scout IDs do not use the `chr` prefix in chromosome names, so any `chr`
/// prefix is removed from compound names before generating identifiers.
///
/// The case identifier in the Genmod annotation is ignored. This keeps the
/// parsing logic independent of the case being loaded, which is important
/// when loading cloned cases with a different case ID.
///
/// The variant type (`clinical` or `research`) is included in the identifier
/// generation.
///
/// # Arguments
///
/// * `compound_info` - Optional raw compound annotation string from Genmod.
/// * `variant_type` - Variant type (`clinical` or `research`) used when generating IDs.
///
/// # Returns
///
/// A vector of compound objects containing:
/// * `display_name` - Compound variant name without a `chr` prefix.
/// * `variant` - MD5 identifier generated from the compound name and variant type.
/// * `score` - Compound score provided by Genmod, or `0.0` if unavailable.
pub fn parse_compounds(compound_info: Option<String>, variant_type: &str) -> Vec<Compound> {
    let mut compounds = Vec::new();

    let Some(compound_info) = compound_info else {
        return compounds;
    };

    for family_info in compound_info.split(',') {
        let split_entry: Vec<&str> = family_info.split(':').collect();

        if split_entry.len() < 2 {
            continue;
        }

        for compound in split_entry[1].split('|') {
            let split_compound: Vec<&str> = compound.split('>').collect();

            if split_compound.is_empty() {
                continue;
            }

            let compound_name = split_compound[0].trim_start_matches("chr");

            let variant_id = generate_md5_key(
                &compound_name
                    .split('_')
                    .chain(std::iter::once(variant_type))
                    .collect::<Vec<_>>(),
            );

            let combined_score = split_compound
                .get(1)
                .and_then(|value| value.parse::<f64>().ok())
                .unwrap_or(0.0);

            compounds.push(Compound {
                display_name: compound_name.to_string(),
                variant: variant_id,
                combined_score,
            });
        }
    }

    compounds
}

/// Updates compound information for a batch of variants.
///
/// For each compound associated with a variant, this function tries to find
/// the referenced variant in the current batch first. If it is not present in
/// the batch, the variant is looked up in MongoDB.
///
/// When the referenced variant is found, the compound is enriched with its
/// rank score, dismissal status, and gene information. Compounds whose
/// referenced variant cannot be found are marked as `not_loaded`.
///
/// This combines the behavior of Scout's `update_compounds` and
/// `update_variant_compounds`.
pub async fn update_compounds(
    loader: &Loader,
    variants: &mut [Document],
) -> Result<(), Box<dyn std::error::Error>> {
    if variants.is_empty() {
        return Ok(());
    }

    // Keep only the information needed to update compounds. This avoids
    // borrowing `variants` while we modify it below.
    let mut variant_lookup: HashMap<String, Document> = HashMap::new();

    for variant in variants.iter() {
        if let Ok(id) = variant.get_str("_id") {
            variant_lookup.insert(id.to_string(), variant.clone());
        }
    }

    let collection = loader.variant_collection();

    for variant in variants.iter_mut() {
        let Some(compounds) = variant.get_array_mut("compounds").ok() else {
            continue;
        };

        for compound in compounds.iter_mut() {
            let Some(compound) = compound.as_document_mut() else {
                continue;
            };

            let Some(compound_variant_id) = compound.get_str("variant").ok().map(str::to_owned)
            else {
                compound.insert("not_loaded", true);
                continue;
            };

            // First look for the referenced variant in the current batch.
            let referenced_variant =
                if let Some(batch_variant) = variant_lookup.get(&compound_variant_id) {
                    Some(batch_variant.clone())
                } else {
                    // If it isn't in the batch, fall back to MongoDB.
                    collection
                        .find_one(doc! { "_id": &compound_variant_id })
                        .await?
                };

            let Some(referenced_variant) = referenced_variant else {
                compound.insert("not_loaded", true);
                continue;
            };

            compound.insert(
                "rank_score",
                referenced_variant
                    .get("rank_score")
                    .cloned()
                    .unwrap_or(Bson::Null),
            );

            let is_dismissed = referenced_variant
                .get_array("dismiss_variant")
                .map(|variants| !variants.is_empty())
                .unwrap_or(false);

            compound.insert("is_dismissed", is_dismissed);

            let genes = referenced_variant
                .get_array("genes")
                .map(|genes| {
                    genes
                        .iter()
                        .filter_map(|gene| {
                            let gene = gene.as_document()?;

                            Some(Bson::Document(doc! {
                                "hgnc_id": gene.get("hgnc_id").cloned().unwrap_or(Bson::Null),
                                "hgnc_symbol": gene
                                    .get("hgnc_symbol")
                                    .cloned()
                                    .unwrap_or(Bson::Null),
                                "region_annotation": gene
                                    .get("region_annotation")
                                    .cloned()
                                    .unwrap_or(Bson::Null),
                                "functional_annotation": gene
                                    .get("functional_annotation")
                                    .cloned()
                                    .unwrap_or(Bson::Null),
                            }))
                        })
                        .collect::<Vec<_>>()
                })
                .unwrap_or_default();

            compound.insert("genes", Bson::Array(genes));
            compound.insert("not_loaded", false);
        }
    }

    Ok(())
}
