use mongodb::bson::{doc, Bson, Document};
use std::collections::HashSet;
use std::collections::HashMap;
use rust_htslib::bcf::Record;
use crate::parse::info::parse_info_string;

use std::sync::LazyLock;

pub static REV_CLINSIG_MAP: LazyLock<HashMap<&'static str, i32>> =
    LazyLock::new(|| {
        HashMap::from([
            ("other", 255),
            ("not_provided", 1),
            ("drug_response", 6),
            ("association_not_found", 13),
            ("risk_factor", 12),
            ("protective", 11),
            ("association", 10),
            ("affects", 9),
            ("histocompatibility", 7),
            ("benign", 2),
            ("likely_benign", 3),
            ("conflicting_interpretations_of_pathogenicity", 8),
            ("conflicting_interpretations", 8),
            ("conflicting_classifications_of_pathogenicity", 8),
            ("uncertain_significance", 0),
            ("likely_pathogenic", 4),
            ("likely_pathogenic,low_penetrance", 4),
            ("pathogenic", 5),
            ("pathogenic,low_penetrance", 5),
        ])
    });

/// Parse ClinVar clinical significance annotations.
///
/// ClinVar annotations have changed format over different versions.
/// This function supports:
///
/// - INFO annotations using `CLNACC` or `CLNVID`
/// - ClinVar significance terms from `CLNSIG`
/// - Review status from `CLNREVSTAT`
/// - Transcript-level ClinVar annotations generated by VEP
///
/// The function returns raw ClinVar annotations. The conversion to the
/// internal Scout representation is handled separately by `build_clnsig()`.
///
/// # Arguments
///
/// * `record` - VCF record containing ClinVar INFO annotations.
/// * `transcripts` - Parsed VEP transcript annotations.
///
/// # Returns
///
/// A vector of BSON documents containing ClinVar significance annotations.
pub fn parse_clnsig(
    record: &Record,
    transcripts: &[Document],
) -> Vec<Document> {
    let mut acc = parse_info_string(record, b"CLNACC")
        .or_else(|| parse_info_string(record, b"CLNVID"))
        .unwrap_or_default();

    let mut sig = parse_info_string(record, b"CLNSIG")
        .unwrap_or_default()
        .to_lowercase();

    let mut revstat = parse_info_string(record, b"CLNREVSTAT")
        .unwrap_or_default()
        .to_lowercase();

    let mut clnsig_accessions = Vec::new();

    // VEP transcript-level ClinVar annotations
    if acc.is_empty() {
        if let Some(first) = transcripts.first() {
            if first.get_array("clnsig").is_ok() {
                let mut values = HashSet::new();

                for transcript in transcripts {
                    if let Ok(annotations) = transcript.get_array("clnsig") {
                        for annotation in annotations {
                            let Some(annotation) = annotation.as_str() else {
                                continue;
                            };

                            for value in annotation.split('/') {
                                values.insert(
                                    value.trim_start_matches('_').to_string(),
                                );
                            }
                        }
                    }
                }

                for value in values {
                    clnsig_accessions.push(doc! {
                        "value": value,
                    });
                }
            }

            // VEP 97+ ClinVar annotations
            if let Ok(clnvid) = first.get_str("clinvar_clnvid") {
                acc = clnvid.to_string();

                if let Ok(value) = first.get_str("clinvar_clnsig") {
                    sig = value.to_lowercase();
                }

                if let Ok(value) = first.get_str("clinvar_revstat") {
                    revstat = value.to_lowercase();
                }
            }
        }
    }

    // New ClinVar format: accession is numeric and significance is textual
    if let Ok(accession) = acc.parse::<i64>() {
        let revstat_groups = revstat
            .replace('&', ",")
            .split(',')
            .filter(|value| !value.is_empty())
            .map(|value| value.trim_start_matches('_').to_string())
            .collect::<Vec<_>>();

        let mut sig_groups = Vec::new();

        for significance in sig.replace('&', ",").split(',') {
            for term in significance.trim_start_matches('_').split('/') {
                sig_groups.push(
                    term
                        .split_whitespace()
                        .collect::<Vec<_>>()
                        .join("_"),
                );
            }
        }

        let sig_groups = parse_clnsig_low_penetrance(sig_groups);

        for value in sig_groups {
            clnsig_accessions.push(doc! {
                "value": value,
                "accession": accession,
                "revstat": revstat_groups.join(","),
            });
        }
    }

    // Old ClinVar format
    if !acc.is_empty() && clnsig_accessions.is_empty() {
        let acc_groups = acc.split('|');
        let sig_groups = sig.split('|');
        let revstat_groups = revstat.split('|');

        for ((acc_group, sig_group), revstat_group) in
            acc_groups.zip(sig_groups).zip(revstat_groups)
        {
            let accessions = acc_group.split(',');
            let significances = sig_group.split(',');
            let revstats = revstat_group.split(',');

            for ((accession, significance), revstat) in
                accessions.zip(significances).zip(revstats)
            {
                if let Ok(value) = significance.parse::<i32>() {
                    clnsig_accessions.push(doc! {
                        "value": value,
                        "accession": accession,
                        "revstat": revstat,
                    });
                }
            }
        }
    }

    clnsig_accessions
}

/// Merge `low_penetrance` clinical significance terms.
///
/// If the term `low_penetrance` immediately follows another clinical
/// significance term, it is appended to the previous term separated by a
/// comma. Otherwise, the term is added as a separate entry.
///
/// # Arguments
///
/// * `sig_groups` - Clinical significance terms.
///
/// # Returns
///
/// A list of clinical significance terms where `low_penetrance` has been
/// merged with the preceding term when applicable.
pub fn parse_clnsig_low_penetrance(
    sig_groups: Vec<String>,
) -> Vec<String> {
    let mut result: Vec<String> = Vec::new();

    for sig in sig_groups {
        if sig == "low_penetrance" && !result.is_empty() {
            if let Some(last) = result.last_mut() {
                last.push(',');
                last.push_str(&sig);
            }
        } else {
            result.push(sig);
        }
    }

    result
}


/// Convert raw ClinVar significance information into the internal format used
/// by Scout.
///
/// ClinVar significance values can be strings or numeric values depending on
/// the annotation format. String values are converted using `REV_CLINSIG_MAP`.
/// Unknown values are assigned the fallback value 255.
///
/// Terms containing `low_penetrance` are annotated with a dedicated flag.
pub fn build_clnsig(clnsig_info: Document) -> Document {
    let value = clnsig_info.get("value");

    let sign_number = match value {
        Some(Bson::String(value)) => {
            REV_CLINSIG_MAP
                .get(value.as_str())
                .copied()
                .unwrap_or(255)
        }
        Some(Bson::Int32(value)) => *value,
        Some(Bson::Int64(value)) => *value as i32,
        _ => 255,
    };

    let mut clnsig_obj = doc! {
        "value": sign_number,
        "accession": clnsig_info.get("accession").cloned(),
        "revstat": clnsig_info.get("revstat").cloned(),
    };

    if let Some(Bson::String(value)) = value {
        if value.contains("low_penetrance") {
            clnsig_obj.insert("low_penetrance", true);
        }
    }

    clnsig_obj
}
